/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define 1 for AIX_CODE_REQUIRED */
/* #undef AIX_CODE_REQUIRED */

/* Define 1 for BIT64 */
#define BIT64 1

/* Define command line support */
#define COMMLINE_SUPPORT 1

/* Define DEBUG flag */
/* #undef DEBUG */

/* Define fine grain mpirun interface support */
#define FINEGRAIN_MPIRUN_INTERFACE 1

/* Define dot for GLUESYM */
#define GLUESYM ""

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <execinfo.h> header file. */
#define HAVE_EXECINFO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define 1 if we have libelf/libelf.h */
#define HAVE_LIBELF_H 1

/* Define to 1 if you have the <libelf/libelf.h> header file. */
/* #undef HAVE_LIBELF_LIBELF_H */

/* Define to 1 if you have the <libgen.h> header file. */
#define HAVE_LIBGEN_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <link.h> header file. */
#define HAVE_LINK_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <poll.h> header file. */
#define HAVE_POLL_H 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/procfs.h> header file. */
#define HAVE_SYS_PROCFS_H 1

/* Define to 1 if you have the <sys/ptrace.h> header file. */
#define HAVE_SYS_PTRACE_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/user.h> header file. */
#define HAVE_SYS_USER_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <thread_db.h> header file. */
#define HAVE_THREAD_DB_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Define lazy binding support */
#define LAZY_BINDING 1

/* Define 1 for LINUX_CODE_REQUIRED */
#define LINUX_CODE_REQUIRED 1

/* Define to header that first defines elf. */
#define LOCATION_OF_LIBELFHEADER <libelf.h>

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1

/* Define 1 for MEASURE_TRACING_COST */
/* #undef MEASURE_TRACING_COST */

/* Define 1 for MPI_BASED */
/* #undef MPI_BASED */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Define 1 if TLS libraries are installed under /lib/tls */
/* #undef NPTL_UNDER_TLS */

/* Name of package */
#define PACKAGE "launchmon"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "ahn1@llnl.gov"

/* Define to the full name of this package. */
#define PACKAGE_NAME "LaunchMON"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "LaunchMON 0.6.4"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "launchmon"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.6.4"

/* Define 1 for PMGR_BASED */
#define PMGR_BASED 1

/* Define 1 for PPC_ARCHITECTURE */
/* #undef PPC_ARCHITECTURE */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define 1 for RM_BGL_MPIRUN */
/* #undef RM_BGL_MPIRUN */

/* Define 1 for RM_SLURM_SRUN */
#define RM_SLURM_SRUN 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* launcher path */
#define TARGET_JOB_LAUNCHER_PATH "/usr/bin/srun"

/* Define test more coll support */
#define TEST_MORE_COLL 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define TOOL_HOST_ENV */
#define TOOL_HOST_ENV "LMON_FE_WHERETOCONNECT_ADDR"

/* Define TOOL_PORT_ENV */
#define TOOL_PORT_ENV "LMON_FE_WHERETOCONNECT_PORT"

/* Define TOOL_SCH_ENV */
#define TOOL_SCH_ENV "LMON_SEC_CHK"

/* Define TOOL_SS_ENV */
#define TOOL_SS_ENV "LMON_SHARED_SECRET"

/* Define USE_VERBOSE_LOGDIR flag */
/* #undef USE_VERBOSE_LOGDIR */

/* Define VERBOSE flag */
/* #undef VERBOSE */

/* Define LOGDIR */
/* #undef VERBOSE_LOGDIR */

/* Version number of package */
#define VERSION "0.6.4"

/* Define 1 for X86_64_ARCHITECTURE */
#define X86_64_ARCHITECTURE 1

/* Define 1 for X86_ARCHITECTURE */
/* #undef X86_ARCHITECTURE */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */
