.TH LaunchMON 3 "MAY 2014" LaunchMON "LaunchMON Back-End API"

.SH NAME
LMON_be_handshake LMON_be_ready \- LaunchMON back-end API: front-end <-> back-end handshake functions. 

.SH SYNOPSIS
.B #include <lmon_be.h>
.PP
.BI "lmon_rc_e LMON_be_handshake ( void *" udata " );"
.PP
.BI "lmon_rc_e LMON_be_ready ( void *" udata " );"
.PP
.B cc ... -lmonbeapi

.SH DESCRIPTION
The \fBLMON_be_handshake()\fR function performs handshake operations 
between the tool front-end and the back-end daemons associated with 
a session (see \fBLMON_launchAndSpawnDaemons\fR(3)). 
For the master daemon, if \fIudata\fR is not NULL and an unpack function 
has been registered (see \fBLMON_be_regUnpackForBeToFe\fR(3)), the client tool data that are bundled 
into the LaunchMON handshaking messages by the front-end 
are de-serialized by that unpack function into the \fIudata\fR argument. 
It is upto the client daemon implementation how these data are distributed 
among the daemons. \fIudata\fR is only meaningful to the 
master daemon. 

\fBLMON_be_ready() \fR is a companion function to \fBLMON_be_handshake()\fR,
which finalizes the handshaking operation 
by sending the \fBREADY\fR message to the front-end.  
For the master daemon, if \fIudata\fR is not NULL and a pack function 
has been registered (see \fBLMON_be_regpackForFeToBe\fR(3)), \fIudata\fR is serialized and bundled into 
the \fBREADY\fR message. \fIudata\fR is only meaningful to the
master daemon. 

Note that all the back-end daemons associated with a session must participate in these functions for a
successful handshake, but the
only master daemon coordinates the communcation with the front-end on
behalf of the other daemons.  

.SH RETURN VALUE
These functions return \fBLMON_OK\fR
on success; otherwise, an LMON error code is returned 
as described below. 

.SH ERRORS
.TP
.B LMON_OK
Success.
.TP
.B LMON_EBDMSG
An LMONP message error. 
.TP
.B LMON_ESYS
A system error (likely attributed to an error in a sockets API call). 
.TP
.B LMON_ESUBCOM
Encountered an error during a communication subsystem operation. 
.TP
.B LMON_ENOMEM
Out of memory.
.TP
.B LMON_EINVAL
Encountered any other erroneous conditions. 

.SH AUTHOR
Dong H. Ahn <ahn1@llnl.gov>

