.TH LaunchMON 3 "MAY 2014" LaunchMON "LaunchMON Front-End API"

.SH NAME
LMON_fe_regErrorCB \- LaunchMON front-end API: registers an error message logging callback function. 

.SH SYNOPSIS
.nf
.B #include <unistd.h>
.B #include <lmon_fe.h>
.B #include <stdarg.h>
.PP
.PP
.BI "lmon_rc_e LMON_fe_regErrorCB ( 
.BI "  int (* " errCB " ) (const char * " format ", va_list " ap "));"
.B cc ... -lmonfeapi

.SH DESCRIPTION

\fBLMON_fe_regErrorCB\fR registers the \fBerrCB\fR function which 
LaunchMON calls back on an error and/or warning condition with 
appropriate arguments. LaunchMON otherwise prints the message 
to the controlling terminal. In case there are multiple callback
functions registered with this API call, the latest one is used.   

.SH RETURN VALUE
\fBLMON_OK\fR on success; otherwise, an LMON error code is returned as described below. 

.SH ERRORS
.TP
.B LMON_OK
Success.
.TP
.B LMON_EBDARG
Invalid arguments.

.SH AUTHOR
Dong H. Ahn <ahn1@llnl.gov>

