.TH LaunchMON 3 "MAY 2014" LaunchMON "LaunchMON Front-End API"

.SH NAME
LMON_fe_createSession \- LaunchMON front-end API: the function creating a tool session.

.SH SYNOPSIS
.B #include <lmon_fe.h>
.PP
.BI "lmon_rc_e LMON_fe_createSession ( int *" sessionHandle " );"
.PP
.B cc ... -lmonfeapi

.SH DESCRIPTION
The \fBLMON_fe_createSession()\fR function creates a tool session, an abstraction
for a group of daemons associated with a parallel job, and
returns the session ID via the \fIsessionHandle\fR argument. 
.PP

.SH RETURN VALUE
The \fBLMON_fe_createSession()\fR function returns \fBLMON_OK\fR
on success; otherwise, an LMON error code is returned 
as described below.

.SH ERRORS
.TP
.B LMON_OK
Success.
.TP
.B LMON_EINVAL
Unable to create resources needed for a tool session.
.TP
.B LMON_ESYS
Encountered a system error. 

.SH AUTHOR
Dong H. Ahn <ahn1@llnl.gov>

