.TH LaunchMON 3 "FEBRUARY 2008" LaunchMON "LaunchMON Front-End API"

.SH NAME
LMON_fe_createSession \- LaunchMON front-end API: the function creating a tool session.

.SH SYNOPSIS
.B #include <lmon_fe.h>
.PP
.BI "lmon_rc_e LMON_fe_createSession ( int *" sessionHandle " );"
.PP
.B cc ... -lmonfeapi

.SH DESCRIPTION
The \fBLMON_fe_createSession()\fR function creates a tool session, an abstraction
for a group of daemons associated with a parallel job, and
returns the session ID via the \fIsessionHandle\fR argument. 
.PP

.SH RETURN VALUE
The \fBLMON_fe_createSession()\fR function returns \fBLMON_OK\fR
on success; otherwise, an LMON error code is returned 
as described below.

.SH ERRORS
.TP
.B LMON_OK
Success.
.TP
.B LMON_EINVAL
Unable to create resources needed for a tool session.
.TP
.B LMON_ESYS
Encountered a system error. 

.SH AUTHOR
Dong H. Ahn <ahn1@llnl.gov>

.SH "SEE ALSO"
.BR LMON_fe_init(3),
.BR LMON_fe_attachAndSpawnDaemons(3),
.BR LMON_fe_launchAndSpawnDaemons(3),
.BR LMON_fe_kill(3),
.BR LMON_fe_detach(3),
.BR LMON_fe_shutdownDaemons(3),
.BR LMON_fe_regUnpackForBeToFe(3),
.BR LMON_fe_regPackForFeToBe(3),
.BR LMON_fe_putToBeDaemonEnv(3),
.BR LMON_fe_sendUsrDataBe(3),
.BR LMON_fe_recvUsrDataBe(3),
.BR LMON_fe_getProctable(3),
.BR LMON_fe_getProctableSize(3),
.BR LMON_fe_getResourceHandle(3),
.BR LMON_fe_regErrorCB(3),
.BR LMON_be_init(3),
.BR LMON_be_finalize(3),
.BR LMON_be_getMyRank(3),
.BR LMON_be_getSize(3),
.BR LMON_be_amIMaster(3),
.BR LMON_be_handshake(3),
.BR LMON_be_ready(3),
.BR LMON_be_barrier(3),
.BR LMON_be_broadcast(3),
.BR LMON_be_gather(3),
.BR LMON_be_scatter(3),
.BR LMON_be_regPackForBeToFe(3),
.BR LMON_be_regUnpackForFeToBe(3),
.BR LMON_be_recvUsrData(3),
.BR LMON_be_sendUsrData(3),
.BR LMON_be_getMyProctab(3),
.BR LMON_be_getMyProctabSize(3)
