.TH LaunchMON 3 "MAY 2014" LaunchMON "LaunchMON Front-End API"

.SH NAME
LMON_fe_init \- LaunchMON front-end API: front-end initialization function. 

.SH SYNOPSIS
.B #include <lmon_fe.h>
.PP
.BI "lmon_rc_e LMON_fe_init ( int " ver " );"
.PP
.B cc ... -lmonfeapi

.SH DESCRIPTION
The \fBLMON_fe_init()\fR function initializes the LaunchMON 
front-end. Specifically, it performs the resource setup 
and sanity checks, including
a version mismatch check between the front-end API library and the
header file. The caller must pass \fBLMON_VERSION\fR, 
a macro defined in the \fBlmon_fe.h\fR file, 
to the \fIver\fR argument for proper version matching. 

.SH RETURN VALUE
The \fBLMON_fe_init()\fR function returns \fBLMON_OK\fR
on success; otherwise, an LMON error code is returned 
as described below.

.SH ERRORS
.TP
.B LMON_OK
Success.
.TP
.B LMON_EINVAL
Version mismatch between the LaunchMON front-end API library and the header file.
.TP
.B LMON_EINIT
Unable to initialize the resources.
.TP
.B LMON_ESYS
Encountered a system error.

.SH AUTHOR
Dong H. Ahn <ahn1@llnl.gov>

